require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4.10
  NewCops: enable
  Exclude:
    - bin/*
    - db/**/*
    - config/environments/*
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Style/StringLiterals:
  Exclude:
    - config/**/*
Style/RedundantFetchBlock:
  Exclude:
    - config/**/*
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false